name: Coverage

# Runs on the default branch only and force-pushes the generated HTML report to
# the `coverage` branch.
on:
  push:
    branches:
      - master

jobs:
  coverage:
    uses: oriontvv/rust-workflows/.github/workflows/coverage.yml@master
    permissions:
      contents: write
    with:
      coverage-branch: coverage
